# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mpKE6uVKK2lXUggK6eussfi-Zz6we04Z
"""

def exchange(won):
  w=won
  fh=w//500
  w%=500

  h=w//100
  w%=100

  f=w//50
  w%=50

  t=w//10
  w%=10

  print('500원 동전의 개수: ',fh,' 100원 동전의 개수: ',h,' 50원 동전의 개수: ',f,' 10원 동전의 개수: ',t)

def get_integer(prompt):
  res=int(input(prompt))
  return res

won=get_integer('동전으로 교환하고자 하는 금액은? ')
exchange(won)