# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Fav3QaBMiFhQecnpgTtdyGQ3Csm4w_Rs
"""



def get_radius(prompt):
  r=int(input(prompt))
  return r;

def get_circle_area(r):
  area=r*r*3.14
  return area;

radius=get_radius('넓이를 구하고자 하는 원의 반지름은? ')
result=get_circle_area(radius)
print('반지름 '+str(radius)+'인 원의 넓이: 3.14 x '+str(radius)+' x '+str(radius)+' = '+str(result))